# Generated by Django 4.2.5 on 2023-09-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.IntegerField()),
                ('released', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('r', 'released'), ('u', 'unreleased')], default='u', max_length=200)),
                ('explicit', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('hip', 'Hip-Hop/Rap'), ('rab', 'R&B'), ('pop', 'Pop'), ('metal', 'Metal'), ('rock', 'Rock'), ('alt', 'Alternative'), ('dance', 'Dance')], default='Pop', max_length=200)),
            ],
        ),
    ]
