# Generated by Django 4.2.5 on 2023-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
